spring.application.name=fixitnow

spring.datasource.url=jdbc:mysql://localhost:3306/fixitnow
spring.datasource.username=root
spring.datasource.password=Vishal2211

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true